=== Kiela94/Prog3b/Uebung2/Uebung2.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT Projekt (Chef?, Mitarbeiter*, Team+, Aufgabe, Zeit)>

<!ELEMENT Chef (Vorname+, Nachname+, ID, Skill*)>
<!ELEMENT Mitarbeiter (Vorname+, Nachname+, ID, Skill*, Vorgesetzter?)>

<!ELEMENT Vorname (#PCDATA)>
<!ELEMENT Nachname (#PCDATA)>
<!ELEMENT Personalnummer (ID)>
<!ELEMENT Vorgesetzter (IDREF)>
<!ELEMENT Skill (#PCDATA)>

<!ELEMENT ID (#PCDATA)>
<!ELEMENT IDREF (#PCDATA)>

<!ELEMENT Team (Teilaufgabe+, Mitarbeitername+)>
<!ELEMENT Mitarbeitername (#PCDATA)>
<!ELEMENT Teilaufgabe (#PCDATA)>
<!ATTLIST Team Teamleiter IDREF #REQUIRED>

<!ELEMENT Aufgabe (#PCDATA)>
<!ELEMENT Zeit (#PCDATA)>

=== Kiela94/Prog3b/Uebung2/Uebung2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Projekt SYSTEM "Uebung2.dtd">

<Projekt Aufgabe="Schreibe ein Buch" Deadline="23453">
    <Mitarbeiter ID="3432" Vorgesetzter="3432"> <!--Der Vorgesetzte hat sich selbst als Referenz-->
        <Vorname>Ralf</Vorname>
        <Nachname>Stoewing</Nachname>
    </Mitarbeiter>
    <Mitarbeiter ID="asdfasd" Vorgesetzte="3223">
        <Vorname>Erik</Vorname>
        <Nachname>Mindermann</Nachname>
        <Skill>Softwareentwickler</Skill>
    </Mitarbeiter>
    <Mitarbeiter ID="asdjkl" Vorgesetzte="dasdfa">
        <Vorname>Natascha</Vorname>
        <Nachname>Meinhardt</Nachname>
        <Skill></Skill>
    </Mitarbeiter>
    
    <Team Teamleiter="201502" Teilaufgabe="" Deadline="">
        <Teammitglied ID="3242"/>
        <Teammitglied ID="2342"/>
        <Teammitglied ID="23432" />
    </Team>
    
</Projekt>
