=== Kiela94/Prog3b/Assignment1/hochschullabore.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    targetNamespace="hsLabSchema"
    xmlns="hsLabSchema"
    elementFormDefault="qualified">
    
<!-- Definitionsbereich simpleType Anfang -->
    
    <!-- Spezieller Datentyp "inventarNr" -->
    <xs:simpleType name="inventarNr">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{3}\.[0-9]{3}"/>
        </xs:restriction>
    </xs:simpleType>
    
<!-- Definitionsbereich simpleType Ende -->
    
<!-- Definitionsbereich element Anfang -->
    
    <xs:element name="Hersteller" type="xs:string"/>
    
    <xs:element name="Besonderheit">
        <xs:complexType mixed="true">
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="Hersteller"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="Beschreibung">
        <xs:complexType mixed="true">
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="Hersteller"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="Erweiterung">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Beschreibung"/>
                <xs:element ref="Besonderheit" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <!-- Hier muss noch eine Referenz auf die Software eingebaut werden -->
    <xs:element name="Anwendungssoftware">
        <xs:complexType>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="lizenz" type="xs:boolean" default="true"/>
        </xs:complexType>
    </xs:element>
    
    <!-- Verweis auf software --> 
    <xs:element name="Betriebssystem">
        <xs:complexType>
            <xs:attribute name="name" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="Rechner">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Betriebssystem"/>
                <xs:element name="Anschaffungsdatum">
                    <xs:complexType>
                        <xs:attribute name="datum" type="xs:date" use="required"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Erweiterung" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="Anwendungssoftware" minOccurs="0" maxOccurs="unbounded"/>
                
                <xs:element ref="Beschreibung"/>
                <xs:element ref="Besonderheit" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="inventarNr" type="inventarNr" use="required"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="Peripherie">
        <xs:complexType>
            <xs:attribute name="inventarNr" type="inventarNr" use="required"/>
            <xs:attribute name="bezeichnung" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    
    
    <!-- Ohne Hardware Tag ... ist besser --> 
    <xs:element name="Hardware">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Peripherie" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="Softwarelizenzen">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Betriebssystem" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="Beschreibung"/>
                            <xs:element ref="Besonderheit" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Anwendungssoftware" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="Beschreibung"/>
                            <xs:element ref="Besonderheit" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                        <xs:attribute name="anzahl" type="xs:int" use="optional"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="Labor">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Rechner" maxOccurs="unbounded"/>
                <xs:element ref="Hardware" minOccurs="0"/>
                <xs:element ref="Softwarelizenzen"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string"/>
            <xs:attribute name="raumNr" type="xs:string"/>
        </xs:complexType>
        <xs:key name="Betriebssystem_key">
            <xs:selector xpath="./Softwarelizenzen/Betriebssystem"/>
            <xs:field xpath="@name"/>
        </xs:key>
        <xs:keyref refer="Betriebssystem_key" name="Betriebssystem_keyref">
            <xs:selector xpath="./Rechner/Betriebssystem"></xs:selector>
            <xs:field xpath="@name"></xs:field>
        </xs:keyref>
        <xs:key name="Anwendungssoftware_key">
            <xs:selector xpath="./Softwarelizenzen/Anwendungssoftware"/>
            <xs:field xpath="@name"/>
        </xs:key>
        <xs:keyref refer="Anwendungssoftware_key" name="Anwendungssoftware_keyref">
            <xs:selector xpath="./Rechner/Anwendungssoftware"/>
            <xs:field xpath="@name"/>
        </xs:keyref>
    </xs:element>
    
    <xs:element name="Hochschullabore">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Labor" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="Labor_unique">
            <xs:selector xpath="./Labor"/>
            <xs:field xpath="@raumNr"/>
        </xs:unique>
        <xs:unique name="Rechner_unique">
            <xs:selector xpath="./Labor/Rechner"/>
            <xs:field xpath="@inventarNr"/>
        </xs:unique>
        <xs:unique name="Peripherie_unique">
            <xs:selector xpath="./Labor/Peripherie"/>
            <xs:field xpath="@inventarNr"/>
        </xs:unique>
    </xs:element>
    
<!-- Definitionsbereich element Ende -->
</xs:schema>

=== Kiela94/Prog3b/Assignment1/Hochschullabore_mit_XML-Schema.xml
<?xml version="1.0" encoding="UTF-8"?>
<Hochschullabore 
    xmlns="hsLabSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="hsLabSchema hochschullabore.xsd">
    <Labor name="Multimedialabor" raumNr="Z2320">
        <Rechner inventarNr="000.002">
            <Anschaffungsdatum datum="2016-10-28"/>
            <Beschreibung>Rechner des Dozenten</Beschreibung>
            <Betriebssystem name="Windows1"/>
        </Rechner>
        <Rechner inventarNr="000.002">
            <Anschaffungsdatum datum="2010-02-01"/>
            <Beschreibung>Dies ist eine kurze Beschreibung des Rechners</Beschreibung>
            <Besonderheit>Mainboard wurde getauscht</Besonderheit>
            <Besonderheit>Gehäuse stark beschädtigt</Besonderheit>
            <Betriebssystem name="Windows10"/>
            <Anwendungssoftware name="eclipse" lizenz="false"/>
            <Anwendungssoftware name="oxygen" lizenz="true"/>
            <Anwendungssoftware name="AdobeReader"/>
            <Erweiterung>
                <Beschreibung>Zusätzliche Festplatte</Beschreibung>
                <Besonderheit><Hersteller>Samsung</Hersteller></Besonderheit>
                <Besonderheit>SSD</Besonderheit>
                <Besonderheit>SATAIII</Besonderheit>
                <Besonderheit>256 GB</Besonderheit>
            </Erweiterung>
            <Erweiterung>
                <Beschreibung>Zusätzlicher Arbeitsspeicher</Beschreibung>
                <Besonderheit>DDR4</Besonderheit>
                <Besonderheit>8GB Riegel</Besonderheit>
            </Erweiterung>
            <Erweiterung>
                <Beschreibung>Dedizierte Grafikkarte von <Hersteller>GIGABYTE</Hersteller></Beschreibung>
            </Erweiterung>
        </Rechner>
        <Rechner inventarNr="000.003">
            <Anschaffungsdatum datum="2010-02-01"/>
            <Beschreibung>Dies ist eine kurze Beschreibung des Rechners</Beschreibung>
            <Besonderheit>Kaugummi im USB Port vorne</Besonderheit>
            <Betriebssystem name="Windows10"/>
            <Anwendungssoftware name="eclipse" lizenz="false"/> 
            <Anwendungssoftware name="oxygen" lizenz="true"/>
            <Anwendungssoftware name="AdobeReader"/>
            <Erweiterung>
                <Beschreibung>zusätzliche Festplatte</Beschreibung>
                <Besonderheit>HDD</Besonderheit>
                <Besonderheit>SATAII</Besonderheit>
                <Besonderheit>1 TB</Besonderheit>
            </Erweiterung>
        </Rechner>
        <Rechner inventarNr="000.004">
            <Anschaffungsdatum datum="2010-02-01"/>
            <Beschreibung>
                CPU: <Hersteller>Intel</Hersteller> Core i5-6500K
                Arbeitsspeicher: 8GB
                Festplatte1: 128 GB SSD
                Festplatte2: 1 TB HDD 
                Busbreite: 64 Bit
                PCI: 3x
                SATAIII: 6x (intern)
                USB 3.1: 1x
                USB 3.1 Typ C: 1x
                USB 3.0: 6x
                USB 2.0: 3x
                Grafik: <Hersteller>NVIDIA</Hersteller> GeForce GTX950
                Optisches Laufwerk: DVD Brenner
                DVI: 2x
                VGA: 1x
                HDMI: 4x
                Displayport: 3x
            </Beschreibung>
            <Betriebssystem name="Windows10"/>
            <Anwendungssoftware name="eclipse" lizenz="false"/> 
            <Anwendungssoftware name="oxygen" lizenz="true"/>
            <Anwendungssoftware name="AdobeReader"/>
            <Erweiterung>
                <Beschreibung>Gaming Mainboard</Beschreibung>
                <Besonderheit>1150 Socket</Besonderheit>
                <Besonderheit>4x DDR3 RAM Slots</Besonderheit>
                <Besonderheit>2 HDMI anschluss</Besonderheit>
            </Erweiterung>
        </Rechner>
        <Hardware>
            <Peripherie inventarNr="000.005" bezeichnung="Drucker"/>
            <Peripherie inventarNr="000.006" bezeichnung="Beamer"/>
            <Peripherie inventarNr="000.007" bezeichnung="Bildschirm"/>
        </Hardware>
        <Softwarelizenzen>
            <Betriebssystem name="Windows10">
                <Beschreibung>Windows10 ist ein gutes Betriebssystem</Beschreibung>
                <Besonderheit>ist ganz gut</Besonderheit>
            </Betriebssystem> 
            <Betriebssystem name="Windows7">
                <Beschreibung>Windows7 war ein sehr geiles Betriebssystem</Beschreibung>
                <Besonderheit>Sehr geil</Besonderheit>
            </Betriebssystem>
            <Anwendungssoftware name="MS-Projekt" anzahl="25">
                <Beschreibung>Text</Beschreibung>
                <Besonderheit>Text</Besonderheit>
            </Anwendungssoftware> 
            <Anwendungssoftware name="Eclipse">
                <Beschreibung>Text</Beschreibung>
                <Besonderheit>Text</Besonderheit>
            </Anwendungssoftware>
            <Anwendungssoftware name="Oxygen">
                <Beschreibung>Text</Beschreibung>
            </Anwendungssoftware>
            <Anwendungssoftware name="AdobeReader">
                <Beschreibung>Text</Beschreibung>
            </Anwendungssoftware>
            <Anwendungssoftware name="AdobePlayer">
                <Beschreibung>Text</Beschreibung>
            </Anwendungssoftware>
        </Softwarelizenzen>
    </Labor>
    <!-- <Labor>
        <Rechner inventarNr="">
            <Anschaffungsdatum/>
            <Beschreibung></Beschreibung>
            <Betriebssystem name=""/>
        </Rechner>
        <Softwarelizenzen>
            <Betriebssystem name="">
                <Beschreibung></Beschreibung>
            </Betriebssystem>
        </Softwarelizenzen>
    </Labor> -->
    <Labor name="Multimedialabor" raumNr="Z2320">
        <Rechner inventarNr="000.001">
            <Anschaffungsdatum datum="2016-10-28"/>
            <Beschreibung></Beschreibung>
            <Betriebssystem name=""/>
        </Rechner>
        <Softwarelizenzen>
            <Betriebssystem name="">
                <Beschreibung></Beschreibung>
            </Betriebssystem>
        </Softwarelizenzen>
    </Labor>
</Hochschullabore>
